#%RAML 1.0 NamedExample
productDetails:
  sourceSystem: SAP NA, SAP EMEA
  id: p1
  name: Silly String
  description: some desc
  productNumber: pn1
  manufacturing: 
    manufactured: false
    daysToManufacture: 7
  pricing: 
    listPrice: 23.24
    costOfGoodsSold: 10.11
    maxDiscountPct: 50
  characteristics: 
    colors: 
      - old gold
      - black
    categories: 
      - fun
    images: 
      - href: http://localhost
        title: image
  packaging: 
    size: "16"
    sizeUnitMeasureCode: oz
    weightUnitMeasureCode: oz
    weight: 16
  modifiedDate: 
    byEmail: 
      type: Work
      address: brett@gmail.com
      preferred: false
      doNotEmail: false
    onDateTime: 2018-01-01T01:01:01Z
  createdDate: 
    byEmail: 
      type: Work
      address: ahyoung@gmail.com
      preferred: false
      doNotEmail: false
    onDateTime: 2018-01-01T01:01:01Z
inventoryDetails:
- sourceSystem: SAP NA
  location: l1
  quantity: 
    onHand: 12
    reserved: 11
    available: 10
    minimumOrderPoint: 50
    minimumOrderQuantity: 10
  dates: 
    expectedArrival: 2018-01-01
    lastReceived: 2018-01-01
  modifiedDate: 
    byEmail: 
      type: Work
      address: brett@gmail.com
      preferred: false
      doNotEmail: false
    onDateTime: 2018-01-01T01:01:01Z
  createdDate: 
    byEmail: 
      type: Work
      address: ahyoung@gmail.com
      preferred: false
      doNotEmail: false
    onDateTime: 2018-01-01T01:01:01Z
- sourceSystem: SAP EMEA
  location: l2
  quantity: 
    onHand: 22
    reserved: 23
    available: 10
    minimumOrderPoint: 50
    minimumOrderQuantity: 10
  dates: 
    expectedArrival: 2018-01-01
    lastReceived: 2018-01-01
  modifiedDate: 
    byEmail: 
      type: Work
      address: brett@gmail.com
      preferred: false
      doNotEmail: false
    onDateTime: 2018-01-01T01:01:01Z
  createdDate: 
    byEmail: 
      type: Work
      address: ahyoung@gmail.com
      preferred: false
      doNotEmail: false
    onDateTime: 2018-01-01T01:01:01Z

  
 