#%RAML 1.0 Library
usage: |
  provides a resuable implementation of the common
  collection - collection member patterns commonly found in RESTful APIs
  along with commonly used query parameters that are applied
  to collection queries to sort and page through result sets

  also sets the default displayNames for each method
  
uses:
  hyper: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/hypermedia-library/1.0.4/hypermedia-library.raml
  common: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/common-library/1.0.12/common-library.raml

types: 
  collectionTotalItems:
    type: integer
    minimum: 0
    
  pagingOffset:
    type: integer
    minimum: 0
    default: 0
    
  pagingLimit:
    type: integer
    minimum: 5
    default: 10
    maximum: 20
    
  sortingSortKey:
    type: string
    
  CollectionResponseMetadata:
    type: common.ResponseMetadata
    properties:
      totalItems?: collectionTotalItems
      pagingOffset?: pagingOffset
      pagingLimit?: pagingLimit
      sortBy?: sortingSortKey
      
  CollectionPagingLinks:
    properties:
      self?: hyper.Link
      first?: hyper.Link
      prev?: hyper.Link
      next?: hyper.Link
      last?: hyper.Link
          
  CollectionResponse:
    type: object
    properties:
      meta?: CollectionResponseMetadata
      links?: CollectionPagingLinks

traits:
  headers: !include /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/rest-headers-trait/1.0.3/rest-headers-trait.raml

resourceTypes:
  collection:
    is: [headers]
    description: |
      the collection of <<resourcePathName>>
    get?:
      displayName: Get <<resourcePathName>>
      description: |
        query the collection of <<resourcePathName | !pluralize>>
        may include optional filtering and sorting criteria
        responses may paginated
      queryParameters: 
        maxResults?: 
          type: number
          default: 25
          example: 25
        pagingOffset?:
          type: number
          default: 1
          example: 1
      responses:
        200:
          description: |
            query on the collection of <<resourcePathName | !pluralize>>
            was successful
          body:
            application/json:
              type: <<resourcePathName | !singularize>>.<<resourcePathName | !singularize | !uppercamelcase>>CollectionResponse
        400: &400responseBadRequest
          description: |
            one or more query parameters was missing, invalid or malformed. 
            the &400responseBadRequest defines a resuable fragment for use throughout the API
            below, you will reference this definition with &400responseBadRequest
          body:
            application/json:
              type: common.Message
        500: &500responseInternalServerError
          description: |
            an internal error occurred that prevented the request from executing
          body:
            application/json:
              type: common.Message
              example: !include /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/500-internal-server-error-response-ex/1.0.1/500-internal-server-error-response-ex.raml

    post?:
      displayName: Post <<resourcePathName>>
      description: |
        create a new member of the collection of <<resourcePathName | !pluralize>>
        from a prototype object
      body: 
        application/json:
          type: <<resourcePathName | !singularize>>.<<resourcePathName | !singularize | !uppercamelcase>>Collection
      responses:
        201: &201responseCreated
          description: |
            a new <<resourcePathName | !singularize>> was created
          body:
            application/json:
              type: object
              properties:
                meta?: CollectionResponseMetadata
                links?: CollectionPagingLinks
                messages:
                  type:  common.Message[]
        202: &202responseAccepted
          description: |
            a new <<resourcePathName | !singularize>> was created
          body:
            application/json:
              type: object
              properties:
                meta?: CollectionResponseMetadata
                links?: CollectionPagingLinks
                messages:
                  type:  common.Message[]
        400: *400responseBadRequest
        409: &409responseConflict
          description: |
            a new <<resourcePathName | !singularize>> was not created due to
            an attempt to violate a system constraint
          body:
            application/json:
              type: common.Message
        500: *500responseInternalServerError
        
  member:
    is: [headers]
    description: |
      an individual <<resourcePathName | !singularize>> within the collection
      of <<resourcePathName | !pluralize>>

    get?:
      displayName: Get <<resourcePathName | !singularize>> by ID
      description: |
        retreive an individual <<resourcePathName | !singularize>>
      responses:
        200: &200responseMember
          description: |
            the <<resourcePathName | !singularize>> was found and retreived
          body:
            application/json:
              type: <<resourcePathName | !singularize>>.<<resourcePathName | !singularize | !uppercamelcase>>
    put?:
      displayName: Put <<resourcePathName | !singularize>> by ID
      description: |
        modify an existing <<resourcePathName | !singularize>>
      body: 
        application/json:
          type: <<resourcePathName | !singularize>>.<<resourcePathName | !singularize | !uppercamelcase>>
      responses:
        202: *202responseAccepted
        400: *400responseBadRequest
        404: &404responseNotFound
          body: 
            application/json:
              type: common.Message
              example: !include /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/404-not-found-response-example/1.0.0/404-not-found-response-example.raml
        409: *409responseConflict
        500: *500responseInternalServerError
    delete?:
      displayName: Delete <<resourcePathName | !singularize>> by ID
      responses: 
        202: *202responseAccepted
        404: *404responseNotFound
        500: *500responseInternalServerError
