mysql:
  host: "mysql.shared.demos.mulesoft.com"
  port: "3306"
  schema: "1platform-products"

api:
  autodiscovery: "15526304"
  
anypoint:
  platform:
    client_id: "37022508df994929960b76d87e7f218b"
    client_secret: "4B9d1974C6fD4F2c8CD1360f1298575F"
    visualizer:
      layer: System